### ISSUE TITLE
[CI] Detect broken internal links in markdown files generated from RST

### ISSUE THREAD

**Issue by fpetrogalli** [ARM-software/acle#104]
**The issue**

The conversion RST to Markdown has lost the ability to detect bugs in internal hyperlinks.

In the RST version, we were checking the internal hyperlinks via `rstcheck`. When going to markdown, sectioning anchors like `ssec-whatever` have lost meaning.

For example, the hyperlink `ssec-whatever_` in the RST sources would point to the following anchor

```
.. _ssec-whatever:

The section title
----------------
```

The translation to mardown via pandoc has lost track of these hyperlink, because in a pandoc (or GitHub) world the header in the example would have been converted in 
```
# The section title
```

For this header, the internal hyperlink would assume the form:`[link text](#the-section-title)`. Therefore, the references using the original anchor name from the RST file like `[link text](#ssec-whatever)` have lost their target and don't map to the correct place in the docs. This can be seen also in issue #7 .

We use `markdown-links-check` to find for broken links, but these internal link errors cannot be detected by `markdown-links-check`.

We know that pandoc doesn't emit warnings for missing internal hyperlinks, and we also know that pdflatex doesn't fail when these links are not resolving correctly. Therefore, we cannot expect neither tools to fail when the internal links are missing.

However, we can run pandoc in `--verbose` mode when generating the PDFs, and we can capture the output of `pdfTeX` which is emitting the following warnings for missing links:

```
pdfTeX warning (dest): name{sec-NEON-intrinsics} has been referenced but does n
ot exist, replaced by a fixed one
```

Therefore, we can produce the list of broken links by extracting all the text inside the `name{...}` text.

One way to produce the full list of all the broken links is the following (this was run on `acle.md` as present in https://github.com/ValeriaDaneva/acle/blob/github.io-rst-to-md/main/acle.md, from #101 ):

```
 pandoc acle.md --verbose --fail-if-warnings -o acle.pdf 2>&1 | grep -E 'pdfTeX warning \(dest\): name{[^}]+}' | sed -E  's/.*name\{([^}]+)\}.*/\1/' | sort | uniq
```

**proposed solution**

A bash script with a function that invokes the comamnd used to generate the list of broken links for all the MDs of the specs, and that fails if such list is not empty. The script needs to be invoked in the workflow `.github/workflows/ci.yml`.

**Comment by ValeriaDaneva** [comment]
Currently being addressed in #112
