### ISSUE TITLE
[BUG] Missing counters in headings

### ISSUE THREAD

**Issue by fpetrogalli** [ARM-software/acle#109]
**Describe the bug**

The counters of the html headers in the NEON specs are showing up in the table of contents, but not in the text of the headers in the body of the document.

**Screenshots**

Here are the headings without the counters, in the body of the doc.
<img width="554" alt="Screenshot 2021-11-09 at 18 09 54" src="https://user-images.githubusercontent.com/25690309/140980530-33c39fef-d83c-40b1-af2f-ab3d1d525b39.png">
Here are the items in the TOC, with the counters.
<img width="466" alt="Screenshot 2021-11-09 at 18 09 31" src="https://user-images.githubusercontent.com/25690309/140980599-ebba803c-b62b-401f-ac41-057925a456c6.png">

**References** 
This problem has been detected while browsing the page at https://arm-software.github.io/acle/neon_intrinsics/advsimd.html#fp16-armv84-a

**Comment by ValeriaDaneva** [comment]
Currently being addressed in #109

**Comment by fpetrogalli** [comment]
This is fixed. Thank you @ValeriaDaneva
