### ISSUE TITLE
[BUG] Navigation bar covering title.

### ISSUE THREAD

**Issue by fpetrogalli** [ARM-software/acle#129]
**Describe the bug**

The pages on github.io do not render correctly on small screens. The navigation bar becomes too tall and covers the title of the page. See this address: https://arm-software.github.io/acle/morello/morello.html

**Screenshots**
I have attached a screenshot of the rendering I see on my 13in laptop.

<img width="1434" alt="Screenshot 2021-11-30 at 19 10 13" src="https://user-images.githubusercontent.com/25690309/144112198-baeea340-9eed-4ec6-b2a1-2fb577f64e51.png">

**Comment by ValeriaDaneva** [comment]
This should be doable with css media queries, although we might have to change quite a few css classes.

**Comment by ValeriaDaneva** [comment]
Being addressed in #137

**Comment by ValeriaDaneva** [comment]
Previous solution abandoned, now being addressed in #138

**Comment by fpetrogalli** [comment]
Thanks to the smaller fonts introduced in #138, the rendering looks good on a 13in screen, so closing this.
<img width="1439" alt="Screenshot 2021-12-13 at 17 46 06" src="https://user-images.githubusercontent.com/25690309/145862354-c4dc970c-be7c-4520-a51c-375cd1be44d8.png">
