### ISSUE TITLE
[BUG] Extra PDF in the artifacts uploaded by the CI

### ISSUE THREAD

**Issue by fpetrogalli** [ARM-software/acle#135]
**Describe the bug**
Runs like [this one](https://github.com/ARM-software/acle/actions/runs/1527480047) are producing a file `tmp.pdf` in the artifacts that is being generated by the script introduced to check the links in the PDF files. 

**Proposed fix**
Delete the file at the end of the script, or avoid targeting the folder `pdfs` for producing the file.

**Comment by ValeriaDaneva** [comment]
Addressed in #136

**Comment by fpetrogalli** [comment]
Fixed in #136
