### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by fpetrogalli** [ARM-software/acle#143]
**Describe the bug**

Some of the C code in the next-release branch of the main ACLE spec is not properly formatted (see screenshot).

The issue is due to the presence of few spaces on the left of the three ` wrapping the code.

**Screenshots**
![Screenshot 2021-12-13 at 15 40 11](https://user-images.githubusercontent.com/25690309/145843466-af869504-d056-4a3e-9e85-93ea49663b69.png)

**Comment by ValeriaDaneva** [comment]
Addressed in #144

**Comment by fpetrogalli** [comment]
Fixed in #144
