### ISSUE TITLE
Arm Neon Intrinsics guarded by `__ARM_FEATURE_SVE`?

### ISSUE THREAD

**Issue by MattPD** [ARM-software/acle#15]
In the 2021Q2 version of neon_intrinsics/advsimd.rst (in the Basic Intrinsics section) the documentation states: "The intrinsics in this section are guarded by the macro ``__ARM_FEATURE_SVE``."

Cf. https://raw.githubusercontent.com/ARM-software/acle/6232924d3a1e5df0dab6dde5472d81a3ec03a391/neon_intrinsics/advsimd.rst

Is it possible that `__ARM_NEON` should be used instead?

**Comment by fpetrogalli** [comment]
🤦 Thank you for reporting this @MattPD. Are you happy to submit a patch for replacing it with the correct macro `__ARM_NEON`?

**Comment by MattPD** [comment]
Sure! Submitted #16

**Comment by fpetrogalli** [comment]
Fixed by #17 .
