### ISSUE TITLE
[BUG] __ARM_FEATURE_CRYPTO replacements have unclear descriptions

### ISSUE THREAD

**Issue by davidben** [ARM-software/acle#152]
**Describe the bug**

In the Q2 2018 version of the document, `__ARM_FEATURE_CRYPTO` was deprecated in favor of finer-grained `__ARM_FEATURE_AES` and `__ARM_FEATURE_SHA2` flags. But the ARM cryptography extension originally covered *four* features: FEAT_AES, FEAT_PMULL, FEAT_SHA1, and FEAT_SHA256.

Given how critical FEAT_PMULL is to AES-GCM, the most common AES mode, I assume the intent was to cover FEAT_PMULL under `__ARM_FEATURE_AES`. But ACLE just says "the AES Crypto instructions from Armv8-A are supported and intrinsics targeting them are available". But looking through "Arm Architecture Reference Manual; Armv8, for A-profile architecture", AES is originally defined under "Armv8.0 Cryptographic Extension", which covers all four. It later says:

> From Armv8.2, an implementation of the Armv8.0 Cryptographic Extension can include either or both of:
> * The AES functionality, including support for multiplication of 64-bit polynomials. The
ID_AA64ISAR0_EL1.AES field indicates whether this functionality is supported.
> * The SHA1 and SHA2-256 functionality. The ID_AA64ISAR0_EL1.{SHA2, SHA1} fields indicate whether
this functionality is supported.

I assume this implies that "the AES crypto instructions" includes pmull? This is confusing because phrase "AES crypto instructions" doesn't appear in the reference manual. Is the terminology defined in another document instead? Either way, this is confusing enough that I think it's simplest for ACLE to list this under `__ARM_FEATURE_AES` explicitly.

Next, ACLE says `__ARM_FEATURE_SHA2` covers "the SHA1 & SHA2 Crypto instructions from Armv8-A are supported", so that covers FEAT_SHA1. This one's okay, but, "SHA2 Crypto instructions" is odd way to refer to SHA-256 because SHA-512 is also in the SHA-2 family. And indeed the ARM reference manual says "SHA2-256". Better to clarify this, especially given...

`__ARM_FEATURE_SHA512` is defined as in terms of "the SHA2 Crypto instructions from Armv8.2-A are supported and intrinsics targeting them". This is extra confusing because A2.3.1 of the reference manual refers to this as. "FEAT_SHA512", "Advanced SIMD SHA512 instructions", and "SHA2-512 functionality". Any reason not to specify SHA-512? Defining it relative to v8.2 is especially confusing because it seems splitting v8.0's crypto extensions into AES/PMULL vs SHA-1/SHA-256 itself dates to v8.2.

**Screenshots**

n/a

**Comment by fpetrogalli** [comment]
Hi @davidben - thank you for your report.

I am writing to you just to confirm that I am looking into this. I agree that there is a degree of vagueness in the way the feature you mention interact with the Arm reference manual.

Here is my understanding of your issue (I made [my own map](#crypto-extensions-overview) of the different crypto extensions), and how it relates with the ArmArm. Please let me know if my reasoning makes sense to you.

> I assume this implies that "the AES crypto instructions" includes pmull?

Yes, I believe so. The [ArmArm](#doc-reference) on page A2-72 says:

> The AES functionality, including support for multiplication of 64-bit polynomials. The ID_AA64ISAR0_EL1.AES field indicates whether this functionality is supported.

This means that `FEAT_AES` and `FEAT_PMULL` need to be paired together
in an implementation.

Please let me know if the [changes](#changes) below sense to you.

Francesco

# Changes

I propose the following improvement:

1. Modify the paragraph under [AES extension](https://github.com/ARM-software/acle/blob/next-release/main/acle.md#aes-extension) specifying that it covers `FEAT_AES` and `FEAT_PMULL` from the cryptographic extensions of Armv8.0.
2. Modify the paragraph under [SHA2 extension](https://github.com/ARM-software/acle/blob/next-release/main/acle.md#sha2-extension) specifying that it covers the `FEAT_SHA1` and `FEAT_SHA256` from the cryptographic extensions of Armv8.0.
3. Modify the paragraph under [SHA512 extensions](https://github.com/ARM-software/acle/blob/next-release/main/acle.md#sha512-extension) specifying that it covers the `FEAT_SHA512` from the cryptographic extension of Armv8.2.

In all three cases, add the complete list of instructions as listed in the [overview](#crypto-extension-overview) below.

# Crypto extension overview

## Doc reference

Source: https://developer.arm.com/documentation/ddi0487/latest, issue G.b released on 22 July 2021

## Armv8.0 cryptographic extensions

From C3.5.30 and A2.3 we gather the following:

1. Table C3-96: Cryptographic Extension of Armv8.0 consist of `FEAT_AES + FEAT_PMULL + FEAT_SHA1 + FEAT_SHA256`
2. Each of `FEAT_*` is made by the following instrucions:
   ```
   FEAT_AES = { AESD, AESE, AESIMC, AESMC }
   FEAT_PMULL =  { PMULL }
   FEAT_SHA1 = {SHA1C, SHA1H, SHA1M, SHA1P, SHA1SU0, SHA1SU1}
   FEAT_SHA256 = {SHA256H, SHA256H2, SHA256SU0, SHA256SU1}
   ```

The term `SHA2-256` is an alias for the feature `FEAT_SHA256`.

> The SHA1 and SHA2-256 functionality. The ID_AA64ISAR0_EL1.{SHA2, SHA1} fields indicate whether this functionality is supported.

## Armv8.2 cryptographic extensions

From A2.3.1, these consist of `FEAT_SHA512 + FEAT_SHA3 + FEAT_SM3 + FEAT_SM4`.

Requirements:

1. `FEAT_SHA512` require `FEAT_SHA1` and `FEAT_SHA256`
2. `FEAT_SHA3` require `FEAT_SHA1` and `FEAT_SHA256`

The features consist of the following instructions:

```
FEAT_SHA512 = {SHA512H, SHA512H2, SHA512SU0, SHA512SU1 }
FEAT_SHA3 = {EOR3, RAX1, XAR, BCAX}
FEAT_SM3 = { SM3SS1, SM3TT1A, SM3TT1B, SM3TT2A, SM3TT2B, SM3PARTW1, SM3PARTW2 }
FEAT_SM4 = { SM4E, SM4EKEY }
```
At the same time, on page pag C3-279 says:

> Implementation of FEAT_SHA512 requires the implementation of the SHA1 and SHA2-256 instructions from the Armv8.0 Cryptographic Extension.

This means that	`FEAT_SHA512` require `FEAT_SHA1` and `FEAT_SHA256`.

**Comment by davidben** [comment]
The reasoning makes sense and defining in terms of `FEAT_*` sounds like a great improvement. Thanks!

**Comment by fpetrogalli** [comment]
@davidben  - I have implemented the fix in #180 . Please let me know if you are happy with the changes. 

Also, please let me know if you are happy for me to add your profile to the list of contributors at https://github.com/ARM-software/acle#contributors-

**Comment by fpetrogalli** [comment]
@allcontributors please add @davidben for bug.

**Comment by fpetrogalli** [comment]
@allcontributors please add @davidben for bug.

**Comment by fpetrogalli** [comment]
@allcontributors please add @davidben for bug.
