### ISSUE TITLE
[BUG] CMSE specs: S --> NS call handling

### ISSUE THREAD

**Issue by 696GrocuttT** [ARM-software/acle#207]
**Describe the bug**

In section 6.6 of CMSE cmse_is_nsfptr() is used to determine if the function pointer is Secure or Non-secure, and whether to cast the pointer back to a normal function pointer before the call. This isn't needed and the associated comments are misleading. The underlying BLXNS instruction that's used to call Non-secure function checks the LSB of the pointer to determine whether to actually transition between states, or stay in the secure state. So effectively the "only branch to non-secure state if cmse_is_nsfptr()" functionality is already build into the instruction. The code should look something like this:
```
void call_callback(void) {
    // As the fp pointer has the cmse_nonsecure_call attribute the compiler 
    // will use a BLXNS instruction for the function call. This instruction 
    // determines whether to perform a Secure --> Non-secure transition, 
    // or state in the Secure state based on the LSB of the pointer (as set by
    // cmse_nsfptr_create() when the callback function was passed to the 
    // Secure state)
    fp();      
}
```

**Comment by 696GrocuttT** [comment]
On a related note, the `bic r1, r1, #1` in example 8.3.1 should be removed, as this should have already been done at the point the function pointer foo was passed to the Secure state, it shouldn't be done at the call site.

**Comment by vhscampos** [comment]
@696GrocuttT  Although not needed, the current example avoids the context stacking and clearing in the case of no state transition.

I propose that we keep the example as an optimisation advice that uses `cmse_is_nsfptr()`.

Then, another example would be added where `fp()` is called as is, with no cast whatsoever. This new example would be the main one in this section.
