### ISSUE TITLE
[BUG] Architecture availability descriptions for RCPC extensions seems backwards

### ISSUE THREAD

**Issue by ktkachov-arm** [ARM-software/acle#238]
**Describe the bug**

In the table at https://github.com/ARM-software/acle/blob/main/main/acle.md#rcpc it says that FEAT_LRCPC is available from Armv8.4 and FEAT_LRCPC2 from Armv8.3, but I believe it should be the other way around: FEAT_LRCPC and the base LDAPR instructions were added in Armv8.3 and extended with the LDAPUR and STLUR variants in Armv8.4 (plus the usual backports to Armv8.2)

**Our commitment**

We will work to solve the bug report in time for the upcoming
release. However, we would like to encourage you to submit the fix
yourself, if possible. If you intend to do so and this is your first
contribution, we recommend reading our [contribution
guidelines](https://github.com/ARM-software/acle/blob/main/CONTRIBUTING.md).

**Comment by vhscampos** [comment]
Fixed in #262
