### ISSUE TITLE
[BUG] [PDF] Identifiers with underscores are not searchable inside paragraphs

### ISSUE THREAD

**Issue by atrosinenko** [ARM-software/acle#282]
# Description

The identifiers with underscores that are typeset as inline code spans cannot be searched for.

The acle.pdf document contains many preprocessor macro names such as `__ARM_FEATURE_CRC32` both inside standalone code blocks and surrounded by other text in a paragraph. These names are visually rendered with underscores, as expected. On the other hand, when searched for with Ctrl+F in a PDF viewer, such identifiers are only found if they are inside standalone blocks of code. This was tested in Okular viewer and the internal PDF viewer integrated into Firefox 121 (snap package on Kubuntu 23.10), but according to [this question](https://tex.stackexchange.com/questions/42777/copy-pasting-of-underscore) on LaTeX StackExchange, this is a known issue affecting underscore character in LaTeX output. The same issues exist in other released PDFs in this repository (maybe except for `mve-<version>.pdf`).

I do understand that PDF format is not always copy-paste friendly, but searching for preprocessor macroses seems to be generally useful and this issue seems to be quite easy to fix.

# How to reproduce

1. Open acle.pdf from the [ACLE 2023 Q2](https://github.com/ARM-software/acle/releases/tag/r2023Q2) release
2. Search for `__ARM_FEATURE_CRC32`
3. Search for `__ARM_FEATURE_FP16_SCALAR_ARITHMETIC`
4. In the Section `3.4.2 <arm_fp16.h>`, copy the last line before the code block into a plain text editor

## Observed behavior

`__ARM_FEATURE_CRC32` is not found at all, `__ARM_FEATURE_FP16_SCALAR_ARITHMETIC` is found 3 times: twice in Section 3.4.2 and once in Section 13.2.5 (always inside a standalone code block).

The last line in section 3.4.2 is copied as

```
ARM FEATURE FP16 SCALAR ARITHMETIC feature macro should be tested before including the header:
```

(note missing underscores).

## Expected behavior

All of the above occurrences are found as well as:
* `__ARM_FEATURE_CRC32` in Section 5.4.12, Section 8.8 as well as in the summary table in Section 5.12
* `__ARM_FEATURE_FP16_SCALAR_ARITHMETIC` in Section 3.4.2 (right before the code block), 5.5.5.1 and others

The last line in section 3.4.2 is copied as

```
__ARM_FEATURE_FP16_SCALAR_ARITHMETIC feature macro should be tested before including the header:
```

# Proposed fix

As suggested in the above question on LaTeX StackExhange, I managed to fix this issue by inserting the

```tex
\usepackage[T1]{fontenc}
```

line right after the `\documentclass` line in the [`tools/acle_template.tex`](https://github.com/ARM-software/acle/blob/main/tools/acle_template.tex) file and rebuilding PDFs with `build_with_docker.sh`. I am not experienced enough in LaTeX to ensure this does not break anything but this looks like a working solution.

**Comment by asl** [comment]
@smithp35 Will you please take a look? Thanks!

**Comment by vhscampos** [comment]
Hi, thanks for your issue report.
If possible, we encourage you to contribute with a Pull Request that addresses this issue. We will be happy to review it.
