### ISSUE TITLE
[BUG] mis-formating of "Availability of Armv8.4-A Advanced SIMD intrinsics" section contents

### ISSUE THREAD

**Issue by rearnsha** [ARM-software/acle#286]
https://arm-software.github.io/acle/main/acle.html#availability-of-armv84-a-advanced-simd-intrinsics

The final bullet point has been mis-formated as a table.  Presumably this is because the raw text contains a `|' character in what was intended to be a regular expression..

**Comment by vhscampos** [comment]
This bug is only present in the HTML version. The PDF looks ok.
