### ISSUE TITLE
[proposal][FMV] Make target_clones and target_version mixable

### ISSUE THREAD

**Issue by DanielKristofKiss** [ARM-software/acle#291]
as proposed https://github.com/llvm/llvm-project/pull/74358#discussion_r1462172419 here let's make possible to mix `target_clones` with `target_version`. 

```c
__attribute__((target_clones("dotprod", "aes"))) 
int callee(void) {
    return 42;
}

__attribute__((target_version("default"))) 
int callee(void) {
    return 0;
}

int caller(void) {
    return callee();
}
```

**Comment by vhscampos** [comment]
Hi, thanks for your issue report.

If possible, we encourage you to contribute with a Pull Request that addresses this issue. We will be happy to review it.

**Comment by labrinea** [comment]
I have created https://github.com/ARM-software/acle/pull/310 for this.
