### ISSUE TITLE
Recognizing  past contributors (pre Open Source release).

### ISSUE THREAD

**Issue by fpetrogalli** [ARM-software/acle#34]
I am going to add past contributors acknowledgment (pre-open source release) via @all-contributors via this issue.

**Comment by fpetrogalli** [comment]
@all-contributors, please add @ktkachov-arm for code, content, infrastructure.

**Comment by fpetrogalli** [comment]
@all-contributors please add @ktkachov-arm for code, content, infrastructure.

**Comment by fpetrogalli** [comment]
@all-contributors please add @sallyarmneale for review.

**Comment by fpetrogalli** [comment]
@all-contributors please add @sbaranga-arm for code.

**Comment by vhscampos** [comment]
I am closing this issue with the assumption that we have finished this work. If we ever find that someone was missed, we will add them independently.
