### ISSUE TITLE
ssec-ls64 link is dead

### ISSUE THREAD

**Issue by PrzemekWirkus** [ARM-software/acle#7]
In paragraph https://github.com/ARM-software/acle/blob/main/main/acle.rst#armv8-7-a-load-store-64-byte-extension there's a link:

* `ssec-LS64` (https://github.com/ARM-software/acle/blob/main/main/acle.rst#ssec-ls64)

which leads to top of ACLE GitHub page instead of LS64 intrinsics (https://github.com/ARM-software/acle/blob/main/main/acle.rst#load-store-64-byte-intrinsics).

I guess this is minor issue with incorrect paragraph linking?

**Comment by fpetrogalli** [comment]
@PrzemekWirkus  - thank you for raising this. 

I have actually checked the link in the latest release in PDF format at https://github.com/ARM-software/acle/releases/tag/r2021-07-02, and it seems to work. Could it be an issue with the way github renders the rst pages?

Francesco

**Comment by vhscampos** [comment]
I am closing this issue as rst documents aren't released anymore.
